//go:build !ignore_autogenerated

// Copyright (c) 2020-2026 Broadcom. All Rights Reserved.
// Broadcom Confidential. The term "Broadcom" refers to Broadcom Inc.
// and/or its subsidiaries.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadNetworkConfiguration) DeepCopyInto(out *WorkloadNetworkConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(WorkloadNetworkConfigurationStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadNetworkConfiguration.
func (in *WorkloadNetworkConfiguration) DeepCopy() *WorkloadNetworkConfiguration {
	if in == nil {
		return nil
	}
	out := new(WorkloadNetworkConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkloadNetworkConfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadNetworkConfigurationList) DeepCopyInto(out *WorkloadNetworkConfigurationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WorkloadNetworkConfiguration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadNetworkConfigurationList.
func (in *WorkloadNetworkConfigurationList) DeepCopy() *WorkloadNetworkConfigurationList {
	if in == nil {
		return nil
	}
	out := new(WorkloadNetworkConfigurationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkloadNetworkConfigurationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadNetworkConfigurationSpec) DeepCopyInto(out *WorkloadNetworkConfigurationSpec) {
	*out = *in
	in.SystemNetworkConfiguration.DeepCopyInto(&out.SystemNetworkConfiguration)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadNetworkConfigurationSpec.
func (in *WorkloadNetworkConfigurationSpec) DeepCopy() *WorkloadNetworkConfigurationSpec {
	if in == nil {
		return nil
	}
	out := new(WorkloadNetworkConfigurationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadNetworkConfigurationStatus) DeepCopyInto(out *WorkloadNetworkConfigurationStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadNetworkConfigurationStatus.
func (in *WorkloadNetworkConfigurationStatus) DeepCopy() *WorkloadNetworkConfigurationStatus {
	if in == nil {
		return nil
	}
	out := new(WorkloadNetworkConfigurationStatus)
	in.DeepCopyInto(out)
	return out
}
