// Copyright (c) 2026 Broadcom. All Rights Reserved.
// Broadcom Confidential. The term "Broadcom" refers to Broadcom Inc.
// and/or its subsidiaries.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *NetworkProviderEntry) DeepCopyInto(out *NetworkProviderEntry) {
	*out = *in
	out.SystemConfiguration = in.SystemConfiguration
}

// DeepCopy returns a deep copy of the receiver.
func (in *NetworkProviderEntry) DeepCopy() *NetworkProviderEntry {
	if in == nil {
		return nil
	}
	out := new(NetworkProviderEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *NetworkProviderSystemConfig) DeepCopyInto(out *NetworkProviderSystemConfig) {
	*out = *in
}

// DeepCopy returns a deep copy of the receiver.
func (in *NetworkProviderSystemConfig) DeepCopy() *NetworkProviderSystemConfig {
	if in == nil {
		return nil
	}
	out := new(NetworkProviderSystemConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *SystemVDSNetworkConfig) DeepCopyInto(out *SystemVDSNetworkConfig) {
	*out = *in
}

// DeepCopy returns a deep copy of the receiver.
func (in *SystemVDSNetworkConfig) DeepCopy() *SystemVDSNetworkConfig {
	if in == nil {
		return nil
	}
	out := new(SystemVDSNetworkConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *WorkloadNetworkConfiguration) DeepCopyInto(out *WorkloadNetworkConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy returns a deep copy of the receiver.
func (in *WorkloadNetworkConfiguration) DeepCopy() *WorkloadNetworkConfiguration {
	if in == nil {
		return nil
	}
	out := new(WorkloadNetworkConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements the runtime.Object interface.
func (in *WorkloadNetworkConfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *WorkloadNetworkConfigurationList) DeepCopyInto(out *WorkloadNetworkConfigurationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WorkloadNetworkConfiguration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *WorkloadNetworkConfigurationList) DeepCopy() *WorkloadNetworkConfigurationList {
	if in == nil {
		return nil
	}
	out := new(WorkloadNetworkConfigurationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements the runtime.Object interface.
func (in *WorkloadNetworkConfigurationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *WorkloadNetworkConfigurationSpec) DeepCopyInto(out *WorkloadNetworkConfigurationSpec) {
	*out = *in
	if in.Providers != nil {
		in, out := &in.Providers, &out.Providers
		*out = make([]NetworkProviderEntry, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *WorkloadNetworkConfigurationSpec) DeepCopy() *WorkloadNetworkConfigurationSpec {
	if in == nil {
		return nil
	}
	out := new(WorkloadNetworkConfigurationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *WorkloadNetworkConfigurationStatus) DeepCopyInto(out *WorkloadNetworkConfigurationStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *WorkloadNetworkConfigurationStatus) DeepCopy() *WorkloadNetworkConfigurationStatus {
	if in == nil {
		return nil
	}
	out := new(WorkloadNetworkConfigurationStatus)
	in.DeepCopyInto(out)
	return out
}
